version: '3.3'
services:
  app:
    build:
      context: .
      args:
        - MIX_ENV=prod
    volumes:
      - .:/code:delegated
      - node_modules:/code/frontend/node_modules:delegated
    ports:
      - 4000:4000
    entrypoint: ""
    command: mix phx.server
    environment: 
      MIX_ENV: prod
volumes:
  node_modules:
